[package]
name = "sg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua.workspace = true
tokio.workspace = true
rmp.workspace = true
rmpv.workspace = true

anyhow = "1"
graphql_client = { version = "0.12.0", features = ["reqwest", "reqwest-blocking"] }
regex = "1.4.6"
reqwest = "0.11.3"
serde = "1.0.125"
futures = "0.3.17"
lsp-server = "0.6.0"
lsp-types = "0.93.2"
serde_json = "1.0"
log4rs = "1.2"
log = "0.4"
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite", "macros", "migrate" ] }

userdata_defaults = { path = "crates/userdata_defaults/" }
dotenv = "0.15.0"
once_cell = "1.17.0"

[workspace.dependencies]
mlua = { version = "0.8", features = ["luajit", "vendored", "module", "serialize", "async"] }
rmp = "0.8.10"
rmpv = "1.0.0"
tokio = { version = "1", features = ["full"] }

[lib]
name = "sg"
path = "lib/sg.rs"

[workspace]
members = [
    "crates/sg-nvim/",
    "crates/userdata_defaults/",
]
