[package]
name = "sg"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua.workspace = true
tokio.workspace = true

anyhow = "1"
graphql_client = { version = "0.13.0", features = ["reqwest", "reqwest-blocking"] }
regex = "1.4.6"
reqwest = "0.11.3"
serde = "1.0.125"
futures = "0.3.17"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
serde_json = "1.0"
log4rs = "1.2"
log = "0.4"
once_cell = "1"

userdata_defaults = { path = "crates/userdata_defaults/" }

[workspace.dependencies]
mlua = { version = "0.8", features = ["luajit", "vendored", "module", "serialize", "async"] }
tokio = { version = "1", features = ["full"] }

[lib]
name = "sg"
path = "lib/sg.rs"

[workspace]
members = [
    "crates/sg-nvim/",
    "crates/userdata_defaults/",
]
