name: nix-build

on:
  pull_request:
    paths:
      - '**.nix'

jobs:
  nix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
      fail-fast: false

    name: nix-build (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # SECURITY: pin third-party action hashes
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
